# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DAQ_GUI_V9.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1072, 613)
        font = QtGui.QFont()
        font.setFamily("Piboto")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.logTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.logTextEdit.setObjectName("logTextEdit")
        self.gridLayout.addWidget(self.logTextEdit, 15, 0, 1, 2)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 17, 0, 1, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.recordButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recordButton.sizePolicy().hasHeightForWidth())
        self.recordButton.setSizePolicy(sizePolicy)
        self.recordButton.setCheckable(False)
        self.recordButton.setChecked(False)
        self.recordButton.setObjectName("recordButton")
        self.gridLayout_2.addWidget(self.recordButton, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.recordingTimeLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.recordingTimeLineEdit.setObjectName("recordingTimeLineEdit")
        self.verticalLayout_4.addWidget(self.recordingTimeLineEdit)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 7, 2, 1, 1)
        self.abortButton = QtWidgets.QPushButton(self.centralwidget)
        self.abortButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.abortButton.sizePolicy().hasHeightForWidth())
        self.abortButton.setSizePolicy(sizePolicy)
        self.abortButton.setMinimumSize(QtCore.QSize(200, 0))
        self.abortButton.setCheckable(False)
        self.abortButton.setObjectName("abortButton")
        self.gridLayout_2.addWidget(self.abortButton, 7, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 4, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.fileName = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileName.sizePolicy().hasHeightForWidth())
        self.fileName.setSizePolicy(sizePolicy)
        self.fileName.setObjectName("fileName")
        self.verticalLayout_3.addWidget(self.fileName)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 2, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_2.addLayout(self.verticalLayout_6, 1, 7, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.browserPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.browserPushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browserPushButton.sizePolicy().hasHeightForWidth())
        self.browserPushButton.setSizePolicy(sizePolicy)
        self.browserPushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.browserPushButton.setAutoFillBackground(False)
        self.browserPushButton.setObjectName("browserPushButton")
        self.verticalLayout_7.addWidget(self.browserPushButton, 0, QtCore.Qt.AlignBottom)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 1, 5, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.AICheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.AICheckBox.setEnabled(True)
        self.AICheckBox.setCheckable(True)
        self.AICheckBox.setObjectName("AICheckBox")
        self.verticalLayout_8.addWidget(self.AICheckBox)
        self.ai_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ai_lineEdit.setEnabled(True)
        self.ai_lineEdit.setObjectName("ai_lineEdit")
        self.verticalLayout_8.addWidget(self.ai_lineEdit)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 1, 6, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 8, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2.addLayout(self.horizontalLayout, 8, 2, 1, 1)
        self.keyboardPushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keyboardPushButton.sizePolicy().hasHeightForWidth())
        self.keyboardPushButton.setSizePolicy(sizePolicy)
        self.keyboardPushButton.setMinimumSize(QtCore.QSize(100, 0))
        self.keyboardPushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.keyboardPushButton.setIconSize(QtCore.QSize(16, 16))
        self.keyboardPushButton.setObjectName("keyboardPushButton")
        self.gridLayout_2.addWidget(self.keyboardPushButton, 7, 5, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 6, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1072, 43))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.menuMain.setFont(font)
        self.menuMain.setObjectName("menuMain")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setCheckable(False)
        self.actionExit.setObjectName("actionExit")
        self.menuMain.addAction(self.actionExit)
        self.menubar.addAction(self.menuMain.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.recordButton.setText(_translate("MainWindow", "Record"))
        self.label_2.setText(_translate("MainWindow", "Recording Time [min]"))
        self.recordingTimeLineEdit.setText(_translate("MainWindow", "2"))
        self.abortButton.setText(_translate("MainWindow", "Abort"))
        self.label.setText(_translate("MainWindow", "File Name"))
        self.fileName.setText(_translate("MainWindow", "/home/pi/Desktop/Data/example.csv"))
        self.browserPushButton.setText(_translate("MainWindow", "..."))
        self.AICheckBox.setText(_translate("MainWindow", "AI Enable"))
        self.keyboardPushButton.setText(_translate("MainWindow", "Keyboard"))
        self.menuMain.setTitle(_translate("MainWindow", "Main"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

